/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.ui.ChatFrame;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Hashtable;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Food;
import model.OrderDetail;

/**
 *
 * @author Nick
 */
public class RestaurantMain extends javax.swing.JFrame {

    /**
     * Creates new form RestaurantMain
     */
    public RestaurantMain() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        factory = Persistence.createEntityManagerFactory(PERSISTENCE_UNIT_NAME);
        em = factory.createEntityManager();

        addFood();
        showTableOrderColumn();
        lblCancelOrder.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        lblTableHeader = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtOriginalPrice = new javax.swing.JTextField();
        cbbDiscount = new javax.swing.JComboBox();
        txtTotalPrice = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        lblCancelOrder = new javax.swing.JLabel();
        lblOrder = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblTable1 = new javax.swing.JLabel();
        rdoTable1 = new javax.swing.JRadioButton();
        lblTable2 = new javax.swing.JLabel();
        rdoTable2 = new javax.swing.JRadioButton();
        lblTable3 = new javax.swing.JLabel();
        rdoTable3 = new javax.swing.JRadioButton();
        lblTable4 = new javax.swing.JLabel();
        rdoTable4 = new javax.swing.JRadioButton();
        lblTable5 = new javax.swing.JLabel();
        rdoTable5 = new javax.swing.JRadioButton();
        lblTable6 = new javax.swing.JLabel();
        rdoTable6 = new javax.swing.JRadioButton();
        lblTable7 = new javax.swing.JLabel();
        rdoTable7 = new javax.swing.JRadioButton();
        lblTable8 = new javax.swing.JLabel();
        rdoTable8 = new javax.swing.JRadioButton();
        lblTable9 = new javax.swing.JLabel();
        rdoTable9 = new javax.swing.JRadioButton();
        lblTable10 = new javax.swing.JLabel();
        rdoTable10 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnEmployeeConf = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        lblHotTea = new javax.swing.JLabel();
        lblBear = new javax.swing.JLabel();
        lblCoffee = new javax.swing.JLabel();
        lblFrechFries = new javax.swing.JLabel();
        lblWine = new javax.swing.JLabel();
        lblCake = new javax.swing.JLabel();
        lblPizza = new javax.swing.JLabel();
        lblBurger = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nick\\Downloads\\1413114511_chef.png")); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Order"));

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblOrder);

        lblTableHeader.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(lblTableHeader)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(lblTableHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Original Price");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Discount");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Total Price");

        cbbDiscount.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "10", "15", "20", "25", "30", "35", "40", "45", "50", " " }));

        jLabel17.setFont(new java.awt.Font("Vladimir Script", 1, 48)); // NOI18N
        jLabel17.setText("Shareton");

        lblCancelOrder.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nick\\Downloads\\cancel.png")); // NOI18N
        lblCancelOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancelOrderMouseClicked(evt);
            }
        });

        lblOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cart.png"))); // NOI18N
        lblOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOrderMouseClicked(evt);
            }
        });

        jLabel7.setText("%");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtOriginalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbbDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTotalPrice)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblOrder)
                .addGap(48, 48, 48)
                .addComponent(lblCancelOrder)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtOriginalPrice, txtTotalPrice});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(txtOriginalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbbDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCancelOrder, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblOrder, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(19, 19, 19))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Table"));

        lblTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTable1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/table.png"))); // NOI18N
        lblTable1.setText("1");

        buttonGroup1.add(rdoTable1);
        rdoTable1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoTable1ActionPerformed(evt);
            }
        });

        lblTable2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTable2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/table.png"))); // NOI18N
        lblTable2.setText("2");

        buttonGroup1.add(rdoTable2);
        rdoTable2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoTable2ActionPerformed(evt);
            }
        });

        lblTable3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTable3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/table.png"))); // NOI18N
        lblTable3.setText("3");

        buttonGroup1.add(rdoTable3);
        rdoTable3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoTable3ActionPerformed(evt);
            }
        });

        lblTable4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTable4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/table.png"))); // NOI18N
        lblTable4.setText("4");

        buttonGroup1.add(rdoTable4);
        rdoTable4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoTable4ActionPerformed(evt);
            }
        });

        lblTable5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTable5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/table.png"))); // NOI18N
        lblTable5.setText("5");

        buttonGroup1.add(rdoTable5);
        rdoTable5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoTable5ActionPerformed(evt);
            }
        });

        lblTable6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTable6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/table.png"))); // NOI18N
        lblTable6.setText("6");

        buttonGroup1.add(rdoTable6);
        rdoTable6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoTable6ActionPerformed(evt);
            }
        });

        lblTable7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTable7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/table.png"))); // NOI18N
        lblTable7.setText("7");

        buttonGroup1.add(rdoTable7);
        rdoTable7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoTable7ActionPerformed(evt);
            }
        });

        lblTable8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTable8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/table.png"))); // NOI18N
        lblTable8.setText("8");

        buttonGroup1.add(rdoTable8);
        rdoTable8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoTable8ActionPerformed(evt);
            }
        });

        lblTable9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTable9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/table.png"))); // NOI18N
        lblTable9.setText("9");

        buttonGroup1.add(rdoTable9);
        rdoTable9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoTable9ActionPerformed(evt);
            }
        });

        lblTable10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTable10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/table.png"))); // NOI18N
        lblTable10.setText("10");

        buttonGroup1.add(rdoTable10);
        rdoTable10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoTable10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTable9)
                            .addComponent(lblTable7)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdoTable9)
                                    .addComponent(rdoTable7)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(rdoTable1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTable3)
                            .addComponent(lblTable1)
                            .addComponent(lblTable5)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdoTable3)
                                    .addComponent(rdoTable5))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTable2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(rdoTable2)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTable4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(rdoTable4)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTable6)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(rdoTable6))))
                    .addComponent(lblTable8)
                    .addComponent(lblTable10)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoTable8)
                            .addComponent(rdoTable10))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTable1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdoTable1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTable2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdoTable2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTable3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdoTable3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTable4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdoTable4)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTable5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdoTable5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTable6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdoTable6)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTable7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdoTable7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTable8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdoTable8)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTable10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdoTable10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTable9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdoTable9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setText("Logout");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Restaurant Management");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Configuration"));

        jButton3.setText("Food");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Chef");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnEmployeeConf.setText("Employee");
        btnEmployeeConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeConfActionPerformed(evt);
            }
        });

        jButton5.setText("Customer");

        jButton6.setText("Report");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmployeeConf, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEmployeeConf, jButton3, jButton4, jButton5, jButton6});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEmployeeConf, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Hello, Nick HO");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Food & Drink"));
        jPanel3.setLayout(new java.awt.GridLayout(5, 0));

        lblHotTea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1413117220_Glass_Teapot_(Yellow).png"))); // NOI18N
        lblHotTea.setText("Hot Tea");
        lblHotTea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHotTeaMouseClicked(evt);
            }
        });
        jPanel3.add(lblHotTea);

        lblBear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1413117806_beer.png"))); // NOI18N
        lblBear.setText("Beer");
        lblBear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBearMouseClicked(evt);
            }
        });
        jPanel3.add(lblBear);

        lblCoffee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1413117123_Coffecup.png"))); // NOI18N
        lblCoffee.setText("Coffee");
        jPanel3.add(lblCoffee);

        lblFrechFries.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1413117160_french_fries.png"))); // NOI18N
        lblFrechFries.setText("Frech Dries");
        jPanel3.add(lblFrechFries);

        lblWine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1413117808_bar_beer.png"))); // NOI18N
        lblWine.setText("Wine");
        jPanel3.add(lblWine);

        lblCake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1413117148_Donut_2.png"))); // NOI18N
        lblCake.setText("Cake");
        jPanel3.add(lblCake);

        lblPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1413117205_pizza_slice_128.png"))); // NOI18N
        lblPizza.setText("Pizza");
        jPanel3.add(lblPizza);

        lblBurger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1413117209_burger.png"))); // NOI18N
        lblBurger.setText("Burger");
        jPanel3.add(lblBurger);

        jScrollPane2.setViewportView(jPanel3);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nick\\Downloads\\chat.png")); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel3)
                        .addGap(25, 25, 25)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jLabel3))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdoTable1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoTable1ActionPerformed
        // TODO add your handling code here:
        choiceTable();
//        if (dtm.getRowCount() > 0) {
//            String message = "You have inserted Food, do you want to cancel Order?";
//            String title = "Warning";
//            int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
//            if (reply == JOptionPane.NO_OPTION) {
//                return;
//            }
//        }

        showTableOrderColumn();
        if (!dtmTM.containsKey("t1")) {
            tblOrder.setModel(dtm);
            lblOrder.setIcon(new ImageIcon("src\\main\\resources\\images\\cart.png"));
            lblCancelOrder.setEnabled(false);
        } else {
            tblOrder.setModel(dtmTM.get("t1"));
            lblOrder.setIcon(new ImageIcon("src\\main\\resources\\images\\payment.png"));
            lblCancelOrder.setEnabled(true);
        }

        txtOriginalPrice.setText(Double.toString(getOriginalPrice()));
    }//GEN-LAST:event_rdoTable1ActionPerformed

    private void rdoTable2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoTable2ActionPerformed
        // TODO add your handling code here:
        choiceTable();
//        if (dtm.getRowCount() > 0) {
//            String message = "You have inserted Food, do you want to cancel Order?";
//            String title = "Warning";
//            int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
//            if (reply == JOptionPane.NO_OPTION) {
//                return;
//            }
//        }

        showTableOrderColumn();
        if (!dtmTM.containsKey("t2")) {
            tblOrder.setModel(dtm);
            lblOrder.setIcon(new ImageIcon("src\\main\\resources\\images\\cart.png"));
            lblCancelOrder.setEnabled(false);
        } else {
            tblOrder.setModel(dtmTM.get("t2"));
            lblOrder.setIcon(new ImageIcon("src\\main\\resources\\images\\payment.png"));
            lblCancelOrder.setEnabled(true);
        }

        txtOriginalPrice.setText(Double.toString(getOriginalPrice()));
    }//GEN-LAST:event_rdoTable2ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        ChatFrame chat = new ChatFrame();
        chat.setVisible(true);

    }//GEN-LAST:event_jLabel6MouseClicked

    private void btnEmployeeConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeConfActionPerformed
        // TODO add your handling code here:
        view.EmployeeView emp = new view.EmployeeView(this, true);
        emp.setVisible(true);
    }//GEN-LAST:event_btnEmployeeConfActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        FoodView food = new FoodView(this, true);
        food.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //Chef chef = new Chef(this,true);
        //chef.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void rdoTable3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoTable3ActionPerformed
        // TODO add your handling code here:
        choiceTable();
    }//GEN-LAST:event_rdoTable3ActionPerformed

    private void rdoTable4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoTable4ActionPerformed
        // TODO add your handling code here:
        choiceTable();
    }//GEN-LAST:event_rdoTable4ActionPerformed

    private void rdoTable5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoTable5ActionPerformed
        // TODO add your handling code here:
        choiceTable();
    }//GEN-LAST:event_rdoTable5ActionPerformed

    private void rdoTable6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoTable6ActionPerformed
        // TODO add your handling code here:
        choiceTable();
    }//GEN-LAST:event_rdoTable6ActionPerformed

    private void rdoTable7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoTable7ActionPerformed
        // TODO add your handling code here:
        choiceTable();
    }//GEN-LAST:event_rdoTable7ActionPerformed

    private void rdoTable8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoTable8ActionPerformed
        // TODO add your handling code here:
        choiceTable();
    }//GEN-LAST:event_rdoTable8ActionPerformed

    private void rdoTable9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoTable9ActionPerformed
        // TODO add your handling code here:
        choiceTable();
    }//GEN-LAST:event_rdoTable9ActionPerformed

    private void rdoTable10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoTable10ActionPerformed
        // TODO add your handling code here:
        choiceTable();
    }//GEN-LAST:event_rdoTable10ActionPerformed

    private void lblHotTeaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHotTeaMouseClicked
        // TODO add your handling code here:
        Food food = new Food();
        food.setFoodName("Tea Hot");
        OrderDetail order = new OrderDetail();
        order.setQuantity(2);
        order.setPrice(250);

        if (!buttonGroup1.isSelected(null)) {
            insertOrder(order, food);
        } else {
            JOptionPane.showMessageDialog(this, "Please select Table", "Warning", JOptionPane.WARNING_MESSAGE, null);
        }
    }//GEN-LAST:event_lblHotTeaMouseClicked

    private void lblBearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBearMouseClicked
        // TODO add your handling code here:
        OrderDetail order = new OrderDetail();
        Food food = new Food();
        food.setFoodName("Beer");
        order.setQuantity(5);
        order.setPrice(15);
        if (!buttonGroup1.isSelected(null)) {
            insertOrder(order, food);
        } else {
            JOptionPane.showMessageDialog(this, "Please select Table", "Warning", JOptionPane.WARNING_MESSAGE, null);
        }
    }//GEN-LAST:event_lblBearMouseClicked

    private void lblOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOrderMouseClicked
        // TODO add your handling code here:
        if (rdoTable1.isSelected() == true && !dtmTM.containsKey("t1") && tblOrder.getRowCount() != 0) {
            dtmTM.put("t1", dtm);
            JOptionPane.showMessageDialog(this, "Order successfully!");
            lblOrder.setIcon(new ImageIcon("C:\\Users\\Nick\\Downloads\\payment.png"));
            lblCancelOrder.setEnabled(true);
            return;
        }
        if (rdoTable2.isSelected() == true && !dtmTM.containsKey("t2") && tblOrder.getRowCount() != 0) {
            dtmTM.put("t2", dtm);
            JOptionPane.showMessageDialog(this, "Order successfully!");
            lblOrder.setIcon(new ImageIcon("C:\\Users\\Nick\\Downloads\\payment.png"));
            lblCancelOrder.setEnabled(true);
            return;
        }

    }//GEN-LAST:event_lblOrderMouseClicked

    private void lblCancelOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelOrderMouseClicked
        // TODO add your handling code here:
        String message = "Are you sure to cancel the Order of ";
        String title = "Confirmation";
        if (rdoTable1.isSelected() == true) {
            int reply = JOptionPane.showConfirmDialog(null, message + "Table 1?", title, JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                dtmTM.remove("t1");
                showTableOrderColumn();
                lblOrder.setIcon(new ImageIcon("src\\main\\resources\\images\\cart.png"));
                txtOriginalPrice.setText(Double.toString(getOriginalPrice()));
                lblCancelOrder.setEnabled(false);
            }
            return;
        }
        if (rdoTable2.isSelected() == true) {
            int reply = JOptionPane.showConfirmDialog(null, message + "Table 2?", title, JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                dtmTM.remove("t2");
                showTableOrderColumn();
                lblOrder.setIcon(new ImageIcon("src\\main\\resources\\images\\cart.png"));
                txtOriginalPrice.setText(Double.toString(getOriginalPrice()));
                lblCancelOrder.setEnabled(false);
            }
            return;
        }
    }//GEN-LAST:event_lblCancelOrderMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestaurantMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestaurantMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestaurantMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestaurantMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestaurantMain().setVisible(true);
            }
        });
    }

    private static final String PERSISTENCE_UNIT_NAME = "RestaurantMgt_jar_1.0-SNAPSHOTPU";
    private static EntityManagerFactory factory;
    private EntityManager em;
    TreeMap<String, DefaultTableModel> dtmTM = new TreeMap<String, DefaultTableModel>();
    DefaultTableModel dtm = null;
    private List<OrderDetail> orders = null;

    private void addFood() {
        JLabel lab1 = new JLabel();
        lab1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nick\\Downloads\\1413117806_beer.png")); // NOI18N
        lab1.setText("Beer");
        jPanel3.add(lab1);

        JLabel lab2 = new JLabel();
        lab2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nick\\Downloads\\1413117160_french_fries.png")); // NOI18N
        lab2.setText("Frech Dries");
        jPanel3.add(lab2);
    }

    private void showTableOrderColumn() {

        Object[] columnNames = {"Food Name", "Quantity", "Price", "Revert", "Reason"};
        dtm = new DefaultTableModel(new Object[0][0], columnNames);
        tblOrder.setModel(dtm);
    }

    private void choiceTable() {
        resetTableChosen();
        if (rdoTable1.isSelected() == true) {
            lblTable1.setForeground(Color.red);
            lblTableHeader.setText("Table 1");
            return;
        }
        if (rdoTable2.isSelected() == true) {
            lblTable2.setForeground(Color.red);
            lblTableHeader.setText("Table 2");
            return;
        }
        if (rdoTable3.isSelected() == true) {
            lblTable3.setForeground(Color.red);
            lblTableHeader.setText("Table 3");
            return;
        }
        if (rdoTable4.isSelected() == true) {
            lblTable4.setForeground(Color.red);
            lblTableHeader.setText("Table 4");
            return;
        }
        if (rdoTable5.isSelected() == true) {
            lblTable5.setForeground(Color.red);
            lblTableHeader.setText("Table 5");
            return;
        }
        if (rdoTable6.isSelected() == true) {
            lblTable6.setForeground(Color.red);
            lblTableHeader.setText("Table 6");
            return;
        }
        if (rdoTable7.isSelected() == true) {
            lblTable7.setForeground(Color.red);
            lblTableHeader.setText("Table 7");
            return;
        }
        if (rdoTable8.isSelected() == true) {
            lblTable8.setForeground(Color.red);
            lblTableHeader.setText("Table 8");
            return;
        }
        if (rdoTable9.isSelected() == true) {
            lblTable9.setForeground(Color.red);
            lblTableHeader.setText("Table 9");
            return;
        }
        if (rdoTable10.isSelected() == true) {
            lblTable10.setForeground(Color.red);
            lblTableHeader.setText("Table 10");
            return;
        }

    }

    private void resetTableChosen() {
        lblTable1.setForeground(Color.black);
        lblTable2.setForeground(Color.black);
        lblTable3.setForeground(Color.black);
        lblTable4.setForeground(Color.black);
        lblTable5.setForeground(Color.black);
        lblTable6.setForeground(Color.black);
        lblTable7.setForeground(Color.black);
        lblTable8.setForeground(Color.black);
        lblTable9.setForeground(Color.black);
        lblTable10.setForeground(Color.black);
    }

    private void insertOrder(OrderDetail order, Food food) {
        Object[] o = new Object[5];
        o[0] = food.getFoodName().trim();
        o[1] = order.getQuantity();
        o[2] = order.getPrice();
        o[3] = order.isIsRevert();
        o[4] = order.getRevertReason();

        if (rdoTable1.isSelected() == true && dtmTM.containsKey("t1")) {
            boolean isDuplicated = false;
            for (int i = 0; i < dtmTM.get("t1").getRowCount(); i++) {
                if (dtmTM.get("t1").getValueAt(i, 0).toString().trim() == food.getFoodName().trim()) {
                    dtmTM.get("t1").setValueAt(Integer.parseInt(dtmTM.get("t1").getValueAt(i, 1).toString()) + 1, i, 1);
                    isDuplicated = true;
                    break;
                }
            }
            if (isDuplicated == false) {
                dtmTM.get("t1").addRow(o);
            }

            tblOrder.setModel(dtmTM.get("t1"));
            txtOriginalPrice.setText(Double.toString(getOriginalPrice()));
            return;
        }
        if (rdoTable2.isSelected() == true && dtmTM.containsKey("t2")) {
            boolean isDuplicated = false;
            for (int i = 0; i < dtmTM.get("t2").getRowCount(); i++) {
                if (dtmTM.get("t2").getValueAt(i, 0).toString().trim() == food.getFoodName().trim()) {
                    dtmTM.get("t2").setValueAt(Integer.parseInt(dtmTM.get("t2").getValueAt(i, 1).toString()) + 1, i, 1);
                    isDuplicated = true;
                    break;
                }
            }
            if (isDuplicated == false) {
                dtmTM.get("t2").addRow(o);
            }

            tblOrder.setModel(dtmTM.get("t2"));
            txtOriginalPrice.setText(Double.toString(getOriginalPrice()));
            return;
        }

        boolean isDuplicated = false;
        for (int i = 0; i < dtm.getRowCount(); i++) {
            if (dtm.getValueAt(i, 0).toString().trim() == food.getFoodName().trim()) {
                dtm.setValueAt(Integer.parseInt(dtm.getValueAt(i, 1).toString()) + 1, i, 1);
                isDuplicated = true;
                break;
            }
        }
        if (isDuplicated == false) {
            dtm.addRow(o);
        }
        tblOrder.setModel(dtm);
        txtOriginalPrice.setText(Double.toString(getOriginalPrice()));
    }

    private double getOriginalPrice() {
        int quantityCol = 1;
        int priceCol = 2;
        double totalPrice = 0;
        DefaultTableModel model = (DefaultTableModel) tblOrder.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            totalPrice += (double) model.getValueAt(i, priceCol) * Integer.parseInt(model.getValueAt(i, quantityCol).toString());
        }
        return totalPrice;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmployeeConf;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbbDiscount;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBear;
    private javax.swing.JLabel lblBurger;
    private javax.swing.JLabel lblCake;
    private javax.swing.JLabel lblCancelOrder;
    private javax.swing.JLabel lblCoffee;
    private javax.swing.JLabel lblFrechFries;
    private javax.swing.JLabel lblHotTea;
    private javax.swing.JLabel lblOrder;
    private javax.swing.JLabel lblPizza;
    private javax.swing.JLabel lblTable1;
    private javax.swing.JLabel lblTable10;
    private javax.swing.JLabel lblTable2;
    private javax.swing.JLabel lblTable3;
    private javax.swing.JLabel lblTable4;
    private javax.swing.JLabel lblTable5;
    private javax.swing.JLabel lblTable6;
    private javax.swing.JLabel lblTable7;
    private javax.swing.JLabel lblTable8;
    private javax.swing.JLabel lblTable9;
    private javax.swing.JLabel lblTableHeader;
    private javax.swing.JLabel lblWine;
    private javax.swing.JRadioButton rdoTable1;
    private javax.swing.JRadioButton rdoTable10;
    private javax.swing.JRadioButton rdoTable2;
    private javax.swing.JRadioButton rdoTable3;
    private javax.swing.JRadioButton rdoTable4;
    private javax.swing.JRadioButton rdoTable5;
    private javax.swing.JRadioButton rdoTable6;
    private javax.swing.JRadioButton rdoTable7;
    private javax.swing.JRadioButton rdoTable8;
    private javax.swing.JRadioButton rdoTable9;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTextField txtOriginalPrice;
    private javax.swing.JTextField txtTotalPrice;
    // End of variables declaration//GEN-END:variables
}
