/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.FlowLayout;
import java.awt.GridLayout;
import javax.swing.JLabel;

/**
 *
 * @author Nick
 */
public class testView extends javax.swing.JFrame {

    /**
     * Creates new form testView
     */
    public testView() {
        initComponents();
        addFood();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        lblHotTea = new javax.swing.JLabel();
        lblBear = new javax.swing.JLabel();
        lblCoffee = new javax.swing.JLabel();
        lblFrechFries = new javax.swing.JLabel();
        lblWine = new javax.swing.JLabel();
        lblCake = new javax.swing.JLabel();
        lblPizza = new javax.swing.JLabel();
        lblBurger = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Food & Drink"));
        jPanel3.setLayout(new java.awt.GridLayout(5, 0));

        lblHotTea.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nick\\Downloads\\1413117220_Glass_Teapot_(Yellow).png")); // NOI18N
        lblHotTea.setText("Hot Tea");
        jPanel3.add(lblHotTea);

        lblBear.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nick\\Downloads\\1413117806_beer.png")); // NOI18N
        lblBear.setText("Beer");
        jPanel3.add(lblBear);

        lblCoffee.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nick\\Downloads\\1413117123_Coffecup.png")); // NOI18N
        lblCoffee.setText("Coffee");
        jPanel3.add(lblCoffee);

        lblFrechFries.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nick\\Downloads\\1413117160_french_fries.png")); // NOI18N
        lblFrechFries.setText("Frech Dries");
        jPanel3.add(lblFrechFries);

        lblWine.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nick\\Downloads\\1413117808_bar_beer.png")); // NOI18N
        lblWine.setText("Wine");
        jPanel3.add(lblWine);

        lblCake.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nick\\Downloads\\1413117148_Donut_2.png")); // NOI18N
        lblCake.setText("Cake");
        jPanel3.add(lblCake);

        lblPizza.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nick\\Downloads\\1413117205_pizza_slice_128.png")); // NOI18N
        lblPizza.setText("Pizza");
        jPanel3.add(lblPizza);

        lblBurger.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nick\\Downloads\\1413117209_burger.png")); // NOI18N
        lblBurger.setText("Burger");
        jPanel3.add(lblBurger);

        jScrollPane1.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(503, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testView().setVisible(true);
            }
        });
    }

    private void addFood() {
//        JLabel lab1 = new JLabel("User Name", JLabel.LEFT);
//        jPanel3.setLayout(new GridLayout(5, 5));
//        jPanel3.add(lab1 = new JLabel("Nick HO"));
        //add(jPanel3);
        
         JLabel lab1 = new JLabel();
         lab1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nick\\Downloads\\1413117806_beer.png")); // NOI18N
        lab1.setText("Beer");
                jPanel3.add(lab1);
        
        JLabel lab2 = new JLabel();
         lab2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nick\\Downloads\\1413117160_french_fries.png")); // NOI18N
        lab2.setText("Frech Dries");
        jPanel3.add(lab2);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBear;
    private javax.swing.JLabel lblBurger;
    private javax.swing.JLabel lblCake;
    private javax.swing.JLabel lblCoffee;
    private javax.swing.JLabel lblFrechFries;
    private javax.swing.JLabel lblHotTea;
    private javax.swing.JLabel lblPizza;
    private javax.swing.JLabel lblWine;
    // End of variables declaration//GEN-END:variables
}
